export enum OmniToken {
  USDT = "nep141:usdt.tether-token.near",
  USDC = "nep141:17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1",
  GONKA = "nep245:v2_1.omni.hot.tg:4444119_wyixUKCL",
  NEAR = "nep141:wrap.near",
  ETH = "nep141:eth.bridge.near",
  AURORA = "nep141:aaaaaa20d9e0e2461697782ef11675f668207961.factory.bridge.near",
  SOL = "nep141:sol.omft.near",
  BNB = "nep245:v2_1.omni.hot.tg:56_11111111111111111111",
  ADI = "nep245:v2_1.omni.hot.tg:36900_11111111111111111111",
}

export enum WalletType {
  NEAR = 1010,
  EVM = 1,
  OMNI = -4,
  SOLANA = 1001,
  STELLAR = 1100,
  TON = 1111,
  COSMOS = 4444118,
  Tron = 333,

  Zcash = -5,
  Btc = -6,
  Xrp = -7,
  Doge = -8,
  Ada = -9,
  Aptos = -10,
  Sui = -11,
  Cardano = -12,
  Litecoin = -14,
  unknown = -1000000,
}

export enum Network {
  Omni_v1 = 0,
  Hot = -4,

  Zcash = -5,
  Btc = -6,
  Xrp = -7,
  Doge = -8,
  Ada = -9,
  Aptos = -10,
  Sui = -11,
  Cardano = -12,
  Litecoin = -14,

  Juno = 4444118,
  Gonka = 4444119,
  OmniTon = 1117,
  ADI = 36900,

  Eth = 1,
  Tron = 333,
  Solana = 1001,
  Stellar = 1100,
  Near = 1010,
  Polygon = 137,
  Arbitrum = 42_161,
  Aurora = 1_313_161_554,
  Avalanche = 43_114,
  Linea = 59_144,
  Xlayer = 196,
  Base = 8453,
  Ton = 1111,
  Bnb = 56,
  OpBnb = 204,
  BnbTestnet = 97,
  Optimism = 10,
  Scroll = 534_352,
  EbiChain = 98_881,
  Sei = 1329,
  Blast = 81_457,
  Taiko = 167_000,
  Mantle = 5000,
  Manta = 169,
  Kava = 2222,
  ZkSync = 324,
  Monad = 10_143,
  Metis = 1088,
  Gnosis = 100,
  Fantom = 250,
  Cronos = 25,
  Chiliz = 88_888,
  Moonbeam = 1284,
  Ronin = 2020,
  Lisk = 1135,
  Sonic = 146,
  Zora = 7_777_777,
  Mode = 34_443,
  Berachain = 80_094,
  Unichain = 130,
  Soneium = 1868,
  Ink = 57_073,
  Apechain = 2741,
}

export interface ChainConfig {
  id: number;
  key: string;
  name: string;
  currency: { id: string; symbol: string; decimals: number; logo: string };
  bridgeContract?: string;
  gasLimit?: bigint;
  logo?: string;
  prefix?: string;
  rpc: string;
  type: WalletType;
}

const rpc = (chain: number) => `https://api0.herewallet.app/api/v1/evm/rpc/${chain}`;
const logo = (chain: number) => `https://storage.herewallet.app/ft/${chain}:native.png`;

const chainsRepository: Record<number, ChainConfig> = {
  [Network.Juno]: {
    id: Network.Juno,
    key: "juno-1",
    name: "Juno",
    bridgeContract: "juno1va9q7gma6l62aqq988gghv4r7u4hnlgm85ssmsdf9ypw77qfwa0qaz7ea4",
    logo: "https://storage.herewallet.app/ft/4444118:ujuno.png",
    currency: { id: "ujuno", symbol: "JUNO", decimals: 6, logo: logo(Network.Juno) },
    rpc: rpc(Network.Juno),
    prefix: "juno",
    type: WalletType.COSMOS,
    gasLimit: 200000n,
  },
  [Network.Gonka]: {
    id: Network.Gonka,
    key: "gonka-mainnet",
    name: "Gonka",
    bridgeContract: "gonka15wng2302rhq5w8ddy3l3jslrhfcpufzfs6wc3zc6cxt8cpwrfp4qqgenkc",
    logo: "https://storage.herewallet.app/ft/4444119:ngonka.png",
    currency: { id: "ngonka", symbol: "GNK", decimals: 6, logo: logo(Network.Gonka) },
    rpc: rpc(Network.Gonka),
    prefix: "gonka",
    type: WalletType.COSMOS,
    gasLimit: 200000n,
  },
  [Network.Monad]: {
    id: Network.Monad,
    key: "monad",
    name: "Monad",
    logo: "https://storage.herewallet.app/upload/8f6bdf0d04494dc7157704cf3a7e623aeba7188120d93535d3b9330fa82fc200.JPG",
    currency: { id: "native", symbol: "MONAD", decimals: 6, logo: logo(Network.Monad) },
    rpc: rpc(Network.Monad),
    type: WalletType.EVM,
  },
  [Network.Near]: {
    id: Network.Near,
    key: "near",
    name: "NEAR",
    logo: "https://storage.herewallet.app/ft/1010:native.png",
    currency: { id: "native", symbol: "NEAR", decimals: 6, logo: logo(Network.Near) },
    rpc: rpc(Network.Near),
    type: WalletType.NEAR,
  },
  [Network.Eth]: {
    id: Network.Eth,
    key: "eth",
    name: "Ethereum",
    logo: "https://storage.herewallet.app/upload/80978f3676fc2dfbd3d874a9421004fb7dea7616481bda53bf68f44e21c3ce0c.png",
    currency: { id: "native", symbol: "ETH", decimals: 18, logo: logo(Network.Eth) },
    rpc: rpc(Network.Eth),
    type: WalletType.EVM,
  },
  [Network.Solana]: {
    id: Network.Solana,
    key: "sol",
    name: "Solana",
    logo: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/solana/info/logo.png",
    currency: { id: "native", symbol: "SOL", decimals: 9, logo: logo(Network.Solana) },
    rpc: rpc(Network.Solana),
    type: WalletType.SOLANA,
  },
  [Network.Arbitrum]: {
    id: Network.Arbitrum,
    key: "arb",
    name: "Arbitrum",
    logo: "https://storage.herewallet.app/upload/1606b00068f729f48de00d2575940484f6a0dc83351702a9fb8b0139e41dc00b.jpeg",
    currency: { id: "native", symbol: "ARB", decimals: 18, logo: logo(Network.Arbitrum) },
    rpc: rpc(Network.Arbitrum),
    type: WalletType.EVM,
  },
  [Network.Base]: {
    id: Network.Base,
    key: "base",
    name: "Base",
    logo: "https://storage.herewallet.app/upload/c6cf6513fba97c22192d0b96ffd2be74608559017a4c41ebf4457b65224a7070.jpg",
    currency: { id: "native", symbol: "BASE", decimals: 18, logo: logo(Network.Base) },
    rpc: rpc(Network.Base),
    type: WalletType.EVM,
  },
  [Network.Bnb]: {
    id: Network.Bnb,
    key: "bsc",
    name: "BNB Chain",
    logo: "https://storage.herewallet.app/upload/b82ec85a318b8d8f1f12b25a0e21cd475208014f15952daf317b876812562530.png",
    currency: { id: "native", symbol: "BNB", decimals: 18, logo: logo(Network.Bnb) },
    rpc: rpc(Network.Bnb),
    type: WalletType.EVM,
  },
  [Network.Polygon]: {
    id: Network.Polygon,
    key: "pol",
    name: "Polygon",
    logo: "https://storage.herewallet.app/upload/e51b9ec8d0ed17792cca05be487f5dbc1d0a1b9113cf7e3465310de48c0acc2f.jpg",
    currency: { id: "native", symbol: "POL", decimals: 18, logo: logo(Network.Polygon) },
    rpc: rpc(Network.Polygon),
    type: WalletType.EVM,
  },
  [Network.Avalanche]: {
    id: Network.Avalanche,
    key: "avax",
    name: "Avalanche",
    logo: "https://storage.herewallet.app/upload/fa027e81ebb6957ebd8feada21b5374b15aa090e1747fae131a1e061d3d7e6da.jpg",
    currency: { id: "native", symbol: "AVAX", decimals: 18, logo: logo(Network.Avalanche) },
    rpc: rpc(Network.Avalanche),
    type: WalletType.EVM,
  },
  [Network.Optimism]: {
    id: Network.Optimism,
    key: "op",
    name: "Optimism",
    logo: "https://storage.herewallet.app/upload/d183a3c76b584552888cb8b5a4dfb849572592d7c7f473fe43bcc5c2adae9a50.jpg",
    currency: { id: "native", symbol: "OP", decimals: 18, logo: logo(Network.Optimism) },
    rpc: rpc(Network.Optimism),
    type: WalletType.EVM,
  },
  [Network.Gnosis]: {
    id: Network.Gnosis,
    key: "gnosis",
    name: "Gnosis",
    logo: "https://storage.herewallet.app/upload/fc4945be03eec20c68ae19920f012afef7204b2c04d39b5cff6ab3a6d99b5981.jpg",
    currency: { id: "native", symbol: "GNO", decimals: 18, logo: logo(Network.Gnosis) },
    rpc: rpc(Network.Gnosis),
    type: WalletType.EVM,
  },
  [Network.Ton]: {
    id: Network.Ton,
    key: "ton",
    name: "TON",
    logo: "https://tgapp.herewallet.app/images/chains/ton.svg",
    currency: { id: "native", symbol: "TON", decimals: 9, logo: logo(Network.Ton) },
    rpc: rpc(Network.Ton),
    type: WalletType.TON,
  },
  [Network.Stellar]: {
    id: Network.Stellar,
    key: "stellar",
    name: "Stellar",
    logo: "https://tgapp.herewallet.app/images/chains/xlm.svg",
    currency: { id: "native", symbol: "XLM", decimals: 6, logo: logo(Network.Stellar) },
    rpc: rpc(Network.Stellar),
    type: WalletType.STELLAR,
  },
  [Network.Btc]: {
    id: Network.Btc,
    key: "btc",
    name: "Bitcoin",
    logo: "https://storage.herewallet.app/ft/-6:native.png",
    currency: { id: "native", symbol: "BTC", decimals: 8, logo: logo(Network.Btc) },
    rpc: rpc(Network.Btc),
    type: WalletType.Btc,
  },
  [Network.Berachain]: {
    id: Network.Berachain,
    key: "bera",
    name: "Berachain",
    logo: "https://storage.herewallet.app/upload/f5c15875b85ca57447ec031930dbdac1f85799a4ca83ae8ecc204142ff433d60.png",
    currency: { id: "native", symbol: "BERA", decimals: 6, logo: logo(Network.Berachain) },
    rpc: rpc(Network.Berachain),
    type: WalletType.EVM,
  },
  [Network.Tron]: {
    id: Network.Tron,
    key: "tron",
    name: "TRON",
    logo: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/tron/info/logo.png",
    currency: { id: "native", symbol: "TRX", decimals: 6, logo: logo(Network.Tron) },
    rpc: rpc(Network.Tron),
    type: WalletType.Tron,
  },
  [Network.Zcash]: {
    id: Network.Zcash,
    key: "zec",
    name: "Zcash",
    logo: "https://storage.herewallet.app/ft/-5:native.png",
    currency: { id: "native", symbol: "ZEC", decimals: 8, logo: logo(Network.Zcash) },
    rpc: rpc(Network.Zcash),
    type: WalletType.Zcash,
  },
  [Network.Xrp]: {
    id: Network.Xrp,
    key: "xrp",
    name: "XRP",
    logo: "https://cryptologos.cc/logos/xrp-xrp-logo.svg?v=040",
    currency: { id: "native", symbol: "XRP", decimals: 6, logo: logo(Network.Xrp) },
    rpc: rpc(Network.Xrp),
    type: WalletType.Xrp,
  },
  [Network.Doge]: {
    id: Network.Doge,
    key: "doge",
    name: "Doge",
    logo: "https://cryptologos.cc/logos/dogecoin-doge-logo.svg?v=040",
    currency: { id: "native", symbol: "DOGE", decimals: 6, logo: logo(Network.Doge) },
    rpc: rpc(Network.Doge),
    type: WalletType.Doge,
  },
  [Network.Ada]: {
    id: Network.Ada,
    key: "ada",
    name: "ADA",
    logo: "https://cryptologos.cc/logos/cardano-ada-logo.svg?v=040",
    currency: { id: "native", symbol: "ADA", decimals: 6, logo: logo(Network.Ada) },
    rpc: rpc(Network.Ada),
    type: WalletType.Ada,
  },
  [Network.Aptos]: {
    id: Network.Aptos,
    key: "aptos",
    name: "Aptos",
    logo: "https://cryptologos.cc/logos/aptos-apt-logo.svg?v=040",
    currency: { id: "native", symbol: "APT", decimals: 6, logo: logo(Network.Aptos) },
    rpc: rpc(Network.Aptos),
    type: WalletType.Aptos,
  },
  [Network.Sui]: {
    id: Network.Sui,
    key: "sui",
    name: "SUI",
    logo: "https://cryptologos.cc/logos/sui-sui-logo.svg?v=040",
    currency: { id: "native", symbol: "SUI", decimals: 6, logo: logo(Network.Sui) },
    rpc: rpc(Network.Sui),
    type: WalletType.Sui,
  },
  [Network.Xlayer]: {
    id: Network.Xlayer,
    key: "xlayer",
    name: "Xlayer",
    logo: "https://storage.herewallet.app/ft/196:native.png",
    currency: { id: "native", symbol: "XLAYER", decimals: 6, logo: logo(Network.Xlayer) },
    rpc: rpc(Network.Xlayer),
    type: WalletType.EVM,
  },
  [Network.Hot]: {
    id: Network.Hot,
    key: "hot",
    name: "Omni",
    logo: "https://tgapp.herewallet.app/images/hot/hot-icon.png",
    currency: { id: "native", symbol: "OMNI", decimals: 6, logo: logo(Network.Hot) },
    rpc: rpc(Network.Hot),
    type: WalletType.OMNI,
  },
  [Network.Cardano]: {
    id: Network.Cardano,
    key: "cardano",
    name: "Cardano",
    logo: "https://cryptologos.cc/logos/cardano-ada-logo.svg?v=040",
    currency: { id: "native", symbol: "ADA", decimals: 6, logo: logo(Network.Cardano) },
    rpc: rpc(Network.Cardano),
    type: WalletType.Cardano,
  },
  [Network.Litecoin]: {
    id: Network.Litecoin,
    key: "ltc",
    name: "Litecoin",
    logo: "https://cryptologos.cc/logos/litecoin-ltc-logo.svg?v=040",
    currency: { id: "native", symbol: "LTC", decimals: 8, logo: logo(Network.Litecoin) },
    rpc: rpc(Network.Litecoin),
    type: WalletType.Litecoin,
  },
  [Network.ADI]: {
    id: Network.ADI,
    key: "adi",
    name: "ADI",
    currency: { id: "native", symbol: "ADI", decimals: 6, logo: logo(Network.ADI) },
    rpc: rpc(Network.ADI),
    type: WalletType.EVM,
  },
};

export const chains = {
  get repository() {
    return Object.values(chainsRepository);
  },

  getByType: (type: WalletType) => Object.values(chainsRepository).filter((chain) => chain.type === type),
  getByKey: (key: string) => {
    const chain = Object.values(chainsRepository).find((chain) => chain.key === key);
    if (!chain) return null;
    return chain;
  },

  get: (id: number) => chainsRepository[id],
  register: (config: ChainConfig) => {
    chainsRepository[config.id] = config;
  },
};
